export const quotes = [
  "Communication leads to community, that is, to understanding, intimacy, and mutual valuing.",
  "The most important thing in communication is hearing what isn't said.",
  "The art of communication is the language of leadership.",
  "Good communication is just as stimulating as black coffee, and just as hard to sleep after.",
  "To effectively communicate, we must realize that we are all different in the way we perceive the world and use this understanding as a guide to our communication with others.",
  "Communication is the solvent of all problems and is the foundation for personal development.",
  "The single biggest problem in communication is the illusion that it has taken place.",
  "Communication works for those who work at it.",
  "The two words 'information' and 'communication' are often used interchangeably, but they signify quite different things. Information is giving out; communication is getting through.",
  "Effective communication is 20% what you know and 80% how you feel about what you know.",
  "The quality of your communication determines the size of your result.",
  "Words are singularly the most powerful force available to humanity. We can choose to use this force constructively with words of encouragement, or destructively using words of despair. Words have energy and power with the ability to help, to heal, to hinder, to hurt, to harm, to humiliate, and to humble.",
  "Communication – the human connection – is the key to personal and career success.",
  "The most important thing in communication is to hear what isn't being said.",
  "Developing excellent communication skills is absolutely essential to effective leadership. The leader must be able to share knowledge and ideas to transmit a sense of urgency and enthusiasm to others. If a leader can't get a message across clearly and motivate others to act on it, then having a message doesn't even matter.",
  "Communication is a skill that you can learn. It's like riding a bicycle or typing. If you're willing to work at it, you can rapidly improve the quality of every part of your life.",
  "Communication is not only the essence of being human, but also a vital property of life.",
  "The way we communicate with others and with ourselves ultimately determines the quality of our lives.",
  "Great communication begins with connection."
];
